# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Download and version data

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  schedule:
     - cron: '41 15 * * *'  # trigger at 3:41 pm UTC (8:41 AM PST)

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.12
      uses: actions/setup-python@v5
      with:
        python-version: "3.12"
        cache: 'pip'
    
    - name: Install dependencies
      run: pip install -r requirements.txt
      
    - name: Run py script to download and pin data
      run: |
        python scripts/read_and_pin_data.py
     
    - name: Check if there are any changes
      id: verify_diff
      run: |
        git config user.name github-actions
        git config user.email github-actions@github.com
        git add -N .
        git diff --quiet . || echo "changed=true" >> $GITHUB_OUTPUT

    - name: Commit and push
      if: steps.verify_diff.outputs.changed == 'true'
      run: |
        git add .
        git commit -m "Add data" -a
        git push
